#!/bin/bash
#
# see http://www.fifi.org/doc/debconf-doc/tutorial.html
# see http://manpages.ubuntu.com/manpages/lucid/man7/debconf-devel.7.html

set -e
umask 022

# Source debconf library.
. /usr/share/debconf/confmodule
db_version 2.0 || { echo "$0: needs DebConf 2.0 or later"; exit 1; }

# db_beginblock

db_input high piwik/automatic-upgrade || true
db_go || true

# db_endblock

exit 0
