#!/bin/sh
set -e

## Remove symlink previous created.

if [ "$1" = "remove" ] || [ "$1" = "purge" ];
then

	if [ -L /etc/lighttpd/conf-available/50-matomo.conf ];
	then
		rm -f /etc/lighttpd/conf-available/50-matomo.conf
		invoke-rc.d lighttpd reload 3>/dev/null || true
	fi

	if [ -e /usr/share/apache2/apache2-maintscript-helper ];
	then
		. /usr/share/apache2/apache2-maintscript-helper
		apache2_invoke disconf matomo.conf || exit $?
		rm -f /etc/apache2/conf-available/matomo.conf
	fi			
fi

#DEBHELPER#
