#!/bin/sh
set -e

## Remove symlink previous created.

if [ -L /etc/lighttpd/conf-available/50-piwik.conf ];
then
	rm -f /etc/lighttpd/conf-available/50-piwik.conf
	# invoke-rc.d lighttpd reload 3>/dev/null || true
fi

if [ -L /etc/apache2/conf.d/piwik.conf ];
then 
	rm -f /etc/apache2/conf.d/piwik.conf
	# invoke-rc.d apache2 reload 3>/dev/null || true
fi

#DEBHELPER#
