#!/bin/sh
set -e

# fix dir permission

chown -R www-data:www-data /var/lib/piwik/data/tmp
chmod -R 0755 /var/lib/piwik/data/tmp

chgrp www-data /etc/piwik 
chmod 0775 /etc/piwik 

chmod 0644 /etc/piwik/*.conf 
chmod 0664 /etc/piwik/*.php 
chgrp www-data /etc/piwik/*.php 
chmod g+w /etc/piwik 

if [ ! -f /etc/lighttpd/conf-available/50-piwik.conf ]; 
then
	if which lighty-enable-mod >/dev/null 2>&1 ;
	then
		ln -s /etc/piwik/lighttpd.conf /etc/lighttpd/conf-available/50-piwik.conf
		invoke-rc.d lighttpd reload 3>/dev/null || true
	else
		echo "Lighttpd not installed, skipping"
	fi
fi

echo "Trying apache2 configuration"
if [ -d /etc/apache2/conf.d ] && [ ! -e /etc/apache2/conf.d/piwik.conf ];
then
	ln -s /etc/piwik/apache.conf /etc/apache2/conf.d/piwik.conf
	invoke-rc.d apache2 reload 3>/dev/null || true
fi


#DEBHELPER#

exit 0
