#!/bin/sh
set -e

# Source debconf library.
. /usr/share/debconf/confmodule
db_version 2.0 || { echo "$0: needs DebConf 2.0 or later"; exit 1; }

# fix dir permission

chown -R www-data:www-data /var/lib/piwik/data/tmp
chmod -R 0755 /var/lib/piwik/data/tmp

chgrp www-data /etc/piwik
chmod 0775 /etc/piwik

chmod 0644 /etc/piwik/*.conf
chmod 0664 /etc/piwik/*.php
chgrp www-data /etc/piwik/*.php
chown www-data /var/log/piwik
chmod g+w /etc/piwik

if [ -f /etc/logrotate.d/piwik-archive/logrotate ];
then
	# fixing problem in piwik 2.12.1-1
	mv -f /etc/logrotate.d/piwik-archive/logrotate /etc/logrotate.d/piwik-log
	echo "  * Moved Piwik logrotate configuration to /etc/logrotate.d/piwik-log"
	rmdir /etc/logrotate.d/piwik-archive/
fi

if which lighty-enable-mod >/dev/null 2>&1 ;
then
	if [ ! -f /etc/lighttpd/conf-available/50-piwik.conf ];
	then
		ln -s /etc/piwik/lighttpd.conf /etc/lighttpd/conf-available/50-piwik.conf
		invoke-rc.d lighttpd reload 2>/dev/null || true
	fi
	echo "  * Check Piwik web configuration in /etc/lighttpd/conf-available/50-piwik.conf"
else
	echo "Lighttpd not installed, skipping"
fi


if [ -d "/etc/apache2/conf.d" ]
then
	if [ ! -e /etc/apache2/conf.d/piwik.conf ];
	then
		ln -s /etc/piwik/apache.conf /etc/apache2/conf.d/piwik.conf
		invoke-rc.d apache2 reload 2>/dev/null || true
	fi
	echo "  * Check Piwik web configuration in /etc/apache2/conf.d/piwik.conf"
else
	echo "Apache2 not installed, skipping"
fi

echo "  * Piwik main configuration files are stored in /etc/piwik/"
echo "  * Piwik crontab file is stored in /etc/cron.d/piwik-archive"
echo "  * When installing/using piwik, make sure you disable any ads blocker"

db_get piwik/automatic-upgrade || true
if [ "$RET" = "true" ]; then
	echo "  * Please wait while Piwik is upgrading..."
	php /usr/share/piwik/console core:update --yes
else
	echo "  * To finish Piwik's upgrade, please run: /usr/bin/php /usr/share/piwik/console core:update"
fi

#DEBHELPER#

exit 0
